In [8]:
from tess_asteroids.utils import target_observability
import numpy as np
import pandas as pd
from tqdm import tqdm

In [2]:
bin_list = pd.read_csv("./data/known_binary_asteroids_20250409.txt")
bin_list

      nid        name prov_desig
0    22.0    Kalliope        NaN
1    31.0  Euphrosyne        NaN
2    41.0      Daphne        NaN
3    45.0     Eugenia        NaN
4    87.0      Sylvia        NaN
..    ...         ...        ...
603   NaN         NaN  2021 DN15
604   NaN         NaN  2021 DS15
605   NaN         NaN   2023 QE6
606   NaN         NaN  2024 XW49
607   NaN         NaN   2024 YU4

[608 rows x 3 columns]

In [78]:
target_observability(target="2013 PY6")

   sector  camera  ccd   dur       vmag
0      31       1    4  15.0  17.586188
1      46       4    3  25.0  25.289462

In [ ]:
bi

In [72]:
observ2 = []

In [74]:
for k, row in tqdm(bin_list.iterrows(), total=len(bin_list), disable=False):
    # if row['nid'] <= 119067:
    #     continue
    if np.isfinite(row['nid']):
        target = f"DES = 2{int(row['nid']):07}"
    else:
        target = row['prov_desig']
    # if target in set([x.target.unique()[0] for x in observ if len(x)>0]):
    #     continue
    df = target_observability(target=target)
    df["target"] = target
    observ2.append(df)

observ2 = pd.concat(observ2, axis=0)

 11%|███████▍                                                          | 68/608 [2:18:34<18:23:27, 122.61s/it]Warning: Target not observed by TESS at defined times.
 16%|██████████▌                                                       | 97/608 [3:17:43<17:23:28, 122.52s/it]Warning: Target not observed by TESS at defined times.
 22%|██████████████                                                   | 131/608 [4:27:00<16:12:24, 122.32s/it]Warning: Target not observed by TESS at defined times.
 27%|█████████████████▌                                               | 164/608 [5:34:10<15:04:20, 122.21s/it]Warning: Target not observed by TESS at defined times.
 28%|██████████████████                                               | 169/608 [5:44:20<14:53:07, 122.07s/it]Warning: Target not observed by TESS at defined times.
 32%|████████████████████▌                                            | 192/608 [6:31:13<14:08:16, 122.35s/it]Warning: Target not observed by TESS at defined times.
 43%|███████████████████████████▊                                     | 260/608 [8:49:54<11:50:56, 122.58s/it]Warning: Target not observed by TESS at defined times.
 44%|████████████████████████████▎                                    | 265/608 [9:00:06<11:39:36, 122.38s/it]Warning: Target not observed by TESS at defined times.
 44%|████████████████████████████▍                                    | 266/608 [9:02:08<11:36:40, 122.22s/it]Warning: Target not observed by TESS at defined times.
 49%|███████████████████████████████▎                                | 297/608 [10:05:21<10:34:30, 122.41s/it]Warning: Target not observed by TESS at defined times.
 54%|███████████████████████████████████▏                             | 329/608 [11:10:37<9:29:00, 122.37s/it]Warning: Target not observed by TESS at defined times.
 55%|███████████████████████████████████▍                             | 332/608 [11:16:44<9:22:53, 122.37s/it]Warning: Target not observed by TESS at defined times.
 60%|██████████████████████████████████████▋                          | 362/608 [12:17:52<8:20:33, 122.09s/it]Warning: Target not observed by TESS at defined times.
 60%|██████████████████████████████████████▊                          | 363/608 [12:19:55<8:18:46, 122.15s/it]Warning: Target not observed by TESS at defined times.
 63%|█████████████████████████████████████████                        | 384/608 [13:02:44<7:37:14, 122.48s/it]Warning: Target not observed by TESS at defined times.
 66%|███████████████████████████████████████████▏                     | 404/608 [13:43:32<6:55:36, 122.24s/it]Warning: Target not observed by TESS at defined times.
 67%|███████████████████████████████████████████▍                     | 406/608 [13:47:36<6:51:15, 122.16s/it]Warning: Target not observed by TESS at defined times.
 67%|███████████████████████████████████████████▌                     | 407/608 [13:49:38<6:48:41, 122.00s/it]Warning: Target not observed by TESS at defined times.
 68%|████████████████████████████████████████████                     | 412/608 [13:59:49<6:39:21, 122.25s/it]Warning: Target not observed by TESS at defined times.
 68%|████████████████████████████████████████████▏                    | 413/608 [14:01:51<6:36:56, 122.14s/it]Warning: Target not observed by TESS at defined times.
 69%|█████████████████████████████████████████████                    | 421/608 [14:18:09<6:20:54, 122.22s/it]Warning: Target not observed by TESS at defined times.
 70%|█████████████████████████████████████████████▍                   | 425/608 [14:26:17<6:12:37, 122.17s/it]Warning: Target not observed by TESS at defined times.
 73%|███████████████████████████████████████████████▎                 | 443/608 [15:02:59<5:36:58, 122.53s/it]Warning: Target not observed by TESS at defined times.
 77%|█████████████████████████████████████████████████▉               | 467/608 [15:52:01<4:47:37, 122.40s/it]Warning: Target not observed by TESS at defined times.
 86%|███████████████████████████████████████████████████████▉         | 523/608 [17:46:26<2:53:55, 122.77s/it]Warning: Target not observed by TESS at defined times.
 98%|█████████████████████████████████████████████████████████████████▎ | 593/608 [20:09:33<30:41, 122.75s/it]Warning: Target not observed by TESS at defined times.
100%|███████████████████████████████████████████████████████████████████| 608/608 [20:40:11<00:00, 122.39s/it]

In [82]:
observ2 = observ2.reset_index(drop=True)
observ2.sector = observ2.sector.astype(int)
observ2.camera = observ2.camera.astype(int)
observ2.ccd = observ2.ccd.astype(int)
observ2.target = [int(x[7:]) if "DES" in x else x for x in observ2.target.values]
observ2

      sector  camera  ccd   dur       vmag      target
0         12       1    3   5.0  11.198833          22
1         29       1    2  20.0  10.899714          22
2         29       1    1   2.0  10.898000          22
3         43       4    4  17.0  11.896333          22
4         44       3    4  23.0  11.526750          22
5         45       2    3  24.0  11.091760          22
6         96       1    2   8.0  10.855889          22
7         75       1    4  25.0  11.026538          31
8         91       2    1  25.0  11.998692          31
9         33       1    2  22.0  12.156522          41
10        70       2    4  24.0  12.261640          41
11        99       1    3  17.0  11.626500          41
12        31       1    4  27.0  11.992607          45
13        44       4    2   4.0  13.456600          45
14        44       4    3  17.0  13.327167          45
15        45       3    2  24.0  13.015960          45
16        46       2    4  25.0  12.510808          45
17        46       1    1   1.0  12.214000          45
18        98       1    3  48.0  12.066204          45
19      1751       4    1   6.0  12.545571          45
20        20       1    4  11.0  12.281417          87
21        51       1    4  24.0  12.045560          87
22        67       1    3  26.0  11.600185          87
23      1751       3    3   0.0  12.452000          87
24      1751       4    2   5.0  12.518167          87
25        70       4    2  24.0  13.494400          90
26        71       2    4  22.0  13.067826          90
27        19       1    4   2.0  12.408667          93
28        70       4    1  24.0  12.614680          93
29        71       1    2  24.0  12.157080          93
30         5       1    4   5.0  12.022833         107
31        98       1    3   0.0  12.026000         107
32        42       2    1  25.0  12.048423         121
33        43       1    4   7.0  11.726125         121
34        72       3    4  24.0  13.859120         121
35        91       1    2  26.0  13.036111         121
36        33       1    2  25.0  11.775346         130
37        45       4    4  24.0  13.872680         130
38        46       3    4  26.0  13.714037         130
39        49       1    3  26.0  12.776444         130
40        80       1    1  25.0  12.156808         130
41         7       1    1  13.0  10.385857         216
42        56       1    3  27.0   9.755893         216
43        91       2    4  26.0  11.944407         216
44        45       4    3  24.0  15.724440         243
45        46       3    3  18.0  15.565947         243
46        46       4    2   8.0  15.435111         243
47      1751       3    3   6.0  14.224571         243
48        45       3    3   6.0  14.943429         283
49        45       4    2  18.0  14.853579         283
50        46       2    1   8.0  14.711333         283
51        46       3    2  17.0  14.545000         283
52        64       1    3   9.0  13.771500         283
53        64       1    4  14.0  13.718267         283
54        71       3    2  22.0  13.239957         317
55        71       2    1   1.0  12.951500         317
56        91       1    2   0.0  12.759000         317
57        91       1    3  24.0  13.135280         317
58        44       4    3  23.0  15.288833         379
59        45       3    2  24.0  15.074480         379
60        46       2    4  26.0  14.730222         379
61        92       3    4   0.0  14.496000         379
62        92       4    1  19.0  14.342333         379
63        38       1    3  16.0  15.317118         617
64        68       1    2   1.0  14.853000         617
65        68       1    1  20.0  14.822619         617
66         1       1    3  26.0  14.435778         624
67        59       1    1  25.0  14.494500         624
68        45       3    3  11.0  13.511583         702
69        45       4    2  11.0  13.391000         702
70        46       2    1   8.0  13.260778         702
71        65       1    1  27.0  12.320964         702
72        81       1    4  13.0  11.947071         702
73        81       1    3   7.0  12.005750         702
74        46       4    4  26.0  15.364667         720
75      1751       2    1   6.0  13.501429         720
76        44       4    4  23.0  16.562375         761
77        45       3    1  24.0  16.277680         761
78        46       2    3  26.0  15.847630         761
79        44       3    4  13.0  13.856071         762
80        44       4    1   8.0  13.682667         762
81        45       2    3   6.0  13.540714         762
82        45       2    2   2.0  13.308667         762
83        46       1    3  26.0  12.827667         762
84        47       1    3   6.0  12.412857         762
85        64       1    4  26.0  12.922519         762
86        92       4    1  25.0  14.781885         762
87        72       3    3  24.0  17.093800         809
88        91       3    4  23.0  15.766333         809
89        34       1    4   6.0  15.791429         854
90        70       4    3  24.0  16.501920         854
91        71       2    4  24.0  16.007480         854
92        42       2    2  25.0  13.972346         939
93      1751       3    2   6.0  15.430143         939
94        60       1    4  19.0  14.024850        1016
95        92       3    3   2.0  16.517000        1052
96        92       4    2  22.0  16.353261        1052
97        96       1    3  18.0  13.907316        1052
98        72       3    4  24.0  15.667120        1089
99        92       1    1  25.0  15.565538        1089
100       83       1    4   1.0  13.054000        1139
101       72       4    3   5.0  17.723833        1169
102       92       2    2  25.0  17.423615        1169
103       13       1    4  18.0  15.712421        1313
104       45       4    3  20.0  17.319571        1313
105       46       3    3  10.0  17.233909        1313
106       46       4    2  14.0  17.129533        1313
107       65       1    3  18.0  16.231842        1313
108       83       1    3  24.0  14.509080        1313
109     1751       1    3   6.0  15.878714        1313
110       18       1    3   3.0  14.863250        1338
111       37       1    3  24.0  15.953000        1338
112       72       3    4  16.0  17.056706        1338
113       72       4    1   7.0  16.911500        1338
114       92       2    4  25.0  16.890308        1338
115       28       1    3   3.0  15.898250        1344
116       43       4    4  18.0  17.412000        1344
117       44       3    1  23.0  16.982708        1344
118       45       1    2  24.0  16.356200        1344
119       75       1    4   0.0  14.980000        1453
120       42       2    4   1.0  16.517000        1480
121       42       1    1  23.0  16.242417        1480
122     1751       3    2   6.0  15.272429        1480
123       15       1    4   0.0  15.066000        1509
124       15       1    3   3.0  15.109500        1509
125       37       2    2  24.0  14.953480        1509
126       59       1    1  16.0  14.655824        1509
127       59       1    3   6.0  14.574429        1509
128       81       1    1   8.0  14.673333        1509
129       12       1    4   1.0  16.924500        1526
130       46       4    2  13.0  18.309429        1526
131       46       4    3  11.0  18.232583        1526
132       67       1    4  14.0  16.340333        1526
133       12       1    2   7.0  15.552625        1626
134       12       1    4  14.0  15.495200        1626
135        7       2    1  24.0  14.820080        1656
136       46       4    3  20.0  16.910810        1656
137       51       2    3  24.0  15.465000        1656
138       42       4    4  25.0  16.238500        1717
139       43       3    1  24.0  15.644440        1717
140       44       1    2  23.0  14.942833        1717
141       65       1    3  27.0  15.549214        1717
142       81       1    4   8.0  14.596556        1727
143       21       1    4  26.0  15.346889        1770
144       39       1    4  27.0  15.731000        1770
145       72       3    4   9.0  17.114300        1770
146       72       4    1  14.0  16.984200        1770
147       91       4    3  26.0  16.781963        1770
148       92       1    1  20.0  16.277476        1770
149       92       1    4   3.0  15.971250        1770
150       93       1    3  24.0  15.684800        1770
151       19       1    4  25.0  14.959885        1798
152       92       3    3  25.0  17.462654        1798
153       96       1    4  16.0  15.336471        1798
154        1       1    1   7.0  14.664750        1803
155       18       1    2   2.0  16.764333        1803
156       18       2    3  20.0  16.794905        1803
157       56       1    4  27.0  15.774857        1803
158       73       2    3  19.0  16.628750        1803
159       73       1    2   1.0  16.702000        1803
160        4       1    3  10.0  15.010545        1830
161       42       3    2  25.0  15.941423        1830
162       43       1    4  24.0  15.269440        1830
163     1751       1    3   6.0  15.364000        1830
164       71       4    4   4.0  18.947600        1862
165       72       2    2  24.0  18.720960        1862
166     1751       1    1   6.0  19.096286        1862
167       12       3    1   3.0  12.992500        1866
168       12       3    4   1.0  13.058000        1866
169       13       3    3   4.0  13.180400        1866
170       13       4    2   8.0  13.396333        1866
171       13       4    3  12.0  13.720538        1866
172       20       3    1  25.0  14.881500        1866
173       71       4    3   0.0  16.864000        1879
174       72       3    2  21.0  16.451955        1879
175       91       4    2  26.0  17.216519        1879
176       92       1    4   0.0  16.888000        1879
177       32       1    1   8.0  14.131000        1934
178       32       1    4  17.0  14.206889        1934
179       50       2    3   7.0  17.379000        1934
180     1751       4    1   6.0  16.283857        1990
181       71       4    1  24.0  16.793480        2006
182       72       2    3  24.0  16.330320        2006
183       91       2    4  26.0  16.920370        2006
184       55       1    3  25.0  14.266846        2019
185       71       4    2  24.0  17.119880        2019
186       72       1    1  24.0  16.614200        2019
187       91       3    2  26.0  14.625000        2019
188        1       1    3  26.0  15.443667        2037
189       21       1    3  11.0  16.553917        2037
190       72       4    4  16.0  18.702706        2037
191       92       3    2  11.0  17.545000        2037
192       92       3    3  12.0  17.313615        2037
193       69       2    3  24.0  16.919640        2044
194       91       3    1  26.0  16.706370        2044
195       11       1    2   2.0  15.870667        2047
196     1751       4    3   6.0  17.118857        2070
197       71       4    4  19.0  17.233250        2080
198       72       2    2  16.0  16.845235        2080
199       72       3    1   7.0  16.597125        2080
200       92       1    1  25.0  16.713731        2080
201       32       1    4   2.0  15.079000        2121
202       45       4    2   7.0  17.699750        2121
203       45       4    3  15.0  17.590375        2121
204       46       3    3  12.0  17.418538        2121
205       70       3    2  10.0  14.716727        2121
206       70       2    1  12.0  14.433000        2121
207       15       1    3  14.0  14.549333        2131
208       36       2    2  24.0  16.067800        2131
209       60       2    3  13.0  15.217071        2131
210       60       1    2  10.0  15.256182        2131
211       15       1    3  20.0  15.810000        2150
212       79       1    4  26.0  16.042556        2150
213       99       2    4   0.0  15.944000        2150
214       43       3    3  24.0  17.160360        2171
215       44       2    4  23.0  16.692250        2171
216     1751       2    4   6.0  16.254000        2171
217     1751       2    1   6.0  16.451143        2178
218       42       1    1   8.0  16.066556        2242
219       42       1    4  15.0  16.031000        2242
220     1751       2    4   6.0  15.351714        2242
221       71       4    3  17.0  17.519667        2280
222       72       2    2  16.0  16.995824        2280
223       91       3    4  23.0  16.918792        2280
224       91       3    1   1.0  16.528000        2280
225       23       1    4  27.0  16.190250        2337
226       91       4    3  20.0  17.341905        2337
227       93       1    4  24.0  16.599760        2337
228       72       4    2  16.0  18.759000        2343
229       72       4    3   6.0  18.684000        2343
230       91       3    4  15.0  17.511875        2343
231       42       4    3   2.0  17.550667        2449
232       87       2    3  18.0  17.322053        2449
233       87       2    4   4.0  17.304600        2449
234       92       4    1  23.0  17.092458        2478
235       92       4    4   0.0  16.953000        2478
236       71       3    4   7.0  16.342500        2486
237       73       1    4  24.0  15.049320        2486
238       91       4    2  13.0  16.492786        2486
239       42       3    2  21.0  16.599682        2500
240       42       2    1   2.0  16.295667        2500
241       43       1    4  24.0  16.026120        2500
242     1751       4    2   6.0  16.355143        2500
243       72       3    4   1.0  17.954000        2516
244       72       4    1  22.0  17.852609        2516
245       92       1    2  25.0  17.912462        2516
246        5       1    3   8.0  14.688000        2535
247       42       3    2  25.0  16.075615        2535
248       43       1    1  24.0  15.337880        2535
249     1751       1    2   6.0  14.805429        2535
250       25       1    4   7.0  15.879500        2577
251       25       1    3  10.0  15.937364        2577
252       43       4    2  24.0  17.637760        2602
253       44       2    1  23.0  17.159125        2602
254     1751       3    1   6.0  16.061429        2602
255       42       1    4   0.0  14.879000        2607
256       43       4    4   9.0  17.499000        2623
257       44       3    4  23.0  17.168833        2623
258       45       2    3  24.0  16.765080        2623
259       46       1    3  21.0  16.275909        2623
260       47       1    3  15.0  15.959688        2623
261       45       4    2  15.0  17.481750        2635
262       45       4    3   7.0  17.344500        2635
263       46       3    3  25.0  17.081269        2635
264       44       4    4  23.0  18.447125        2680
265       45       3    1  24.0  18.207040        2680
266       46       2    3  26.0  17.808926        2680
267       37       1    3  13.0  15.410071        2691
268       72       3    4  24.0  18.007480        2691
269       92       3    3   9.0  17.896400        2691
270       92       4    2  15.0  17.777250        2691
271       71       3    4   2.0  17.286000        2754
272       71       4    1  21.0  17.091955        2754
273       72       1    2  24.0  16.630880        2754
274       91       1    1  26.0  17.609222        2754
275       72       3    4  12.0  17.787692        2815
276       72       4    1  11.0  17.665667        2815
277       91       4    4  26.0  16.729259        2815
278       92       1    3  25.0  15.985423        2815
279       18       1    4  23.0  14.977375        2825
280       72       4    1   7.0  18.152625        2825
281       72       4    4  16.0  18.089176        2825
282       92       2    4  23.0  17.559208        2825
283       92       1    1   2.0  17.254667        2825
284       42       3    4  25.0  16.459192        2847
285       43       2    3  24.0  15.869960        2847
286     1751       2    3   6.0  15.654286        2847
287        9       1    3  24.0  16.393000        2860
288       47       2    3   3.0  15.320500        2860
289       64       1    2  26.0  17.121704        2860
290       20       1    4  26.0  15.746630        2871
291       72       4    4  24.0  18.062840        2871
292       92       3    2  25.0  16.802577        2871
293       95       1    3  10.0  14.986636        2871
294       95       1    4  11.0  14.904750        2871
295       30       1    4  27.0  15.855250        2873
296       44       4    2  23.0  18.116458        2873
297       45       2    1   2.0  17.916667        2873
298       45       2    2   5.0  17.540333        2873
299       46       1    2  26.0  17.143889        2873
300       92       4    1   6.0  18.510286        2881
301       92       4    4  17.0  18.414500        2881
302       92       4    3  10.0  18.378182        2883
303       43       4    1   9.0  18.500800        2966
304       44       2    2  23.0  18.184958        2966
305       45       1    3  24.0  17.640560        2966
306     1751       3    3   6.0  17.502143        2966
307       45       4    1  24.0  18.193200        3034
308       46       3    1  26.0  17.864815        3034
309       66       1    3  12.0  14.570154        3034
310       54       1    3  21.0  16.986409        3073
311       71       4    2  24.0  17.267280        3073
312       72       2    4  24.0  16.724800        3073
313       91       4    1  26.0  17.873630        3073
314       54       1    4  19.0  15.568900        3076
315       72       3    3  24.0  18.308160        3076
316       91       4    1  17.0  17.464778        3076
317       91       3    4   7.0  17.092375        3076
318       10       2    3   5.0  17.398500        3122
319       36       1    3  10.0  17.532364        3122
320       36       1    4  12.0  17.551692        3122
321        4       2    3  18.0  15.215579        3169
322       27       1    4   3.0  14.708000        3169
323       44       4    3   7.0  16.702500        3169
324       44       4    4  12.0  16.531308        3169
325       45       3    1   6.0  16.369857        3169
326       45       3    4  17.0  16.151167        3169
327       46       2    2   4.0  15.910400        3169
328       48       2    4  15.0  14.851250        3169
329       48       2    3   9.0  14.956000        3169
330       69       2    2   3.0  15.658750        3169
331       72       4    3   2.0  18.357000        3187
332       92       3    3  23.0  17.983500        3187
333       92       4    2   2.0  17.812333        3187
334       44       4    1  23.0  16.985458        3220
335       45       2    2   8.0  16.753111        3220
336       45       3    1  15.0  16.544438        3220
337       46       1    2  26.0  16.097444        3220
338       47       1    4  10.0  15.404818        3220
339       11       1    2  27.0  18.553464        3255
340       27       1    2   2.0  16.742667        3255
341       45       4    4   2.0  18.397000        3255
342       46       4    2  23.0  18.414375        3255
343       46       4    3   1.0  18.355500        3255
344       66       1    1   3.0  18.446750        3255
345       84       2    4  21.0  14.804727        3255
346       44       3    3  17.0  18.770333        3336
347       44       4    2   5.0  18.612000        3336
348       45       2    4  24.0  18.416500        3336
349       45       2    1   4.0  18.271600        3336
350       46       1    4  26.0  17.790741        3336
351       10       1    3   3.0  16.998000        3378
352       10       1    4  19.0  16.948600        3378
353       44       4    1  23.0  18.024500        3378
354       45       2    2   9.0  17.769700        3378
355       45       3    1  13.0  17.538929        3378
356       46       1    2  26.0  17.079556        3378
357       47       1    4  13.0  16.266786        3378
358       84       1    4  23.0  16.334333        3378
359       71       4    1  24.0  17.934200        3390
360       72       1    2  24.0  17.382640        3390
361       91       4    3  26.0  16.651778        3390

In [86]:
observ2.shape

(2184, 6)

In [85]:
observ2.iloc[-10:]

      sector  camera  ccd   dur       vmag     target
2174      45       1    4  24.0  23.500560  2024 XW49
2175      71       3    2  24.0  23.588280  2024 XW49
2176      72       1    4  24.0  23.524680  2024 XW49
2177    1751       3    4   6.0  23.555000  2024 XW49
2178       5       2    3   6.0  24.173857   2024 YU4
2179       5       2    4  15.0  24.159375   2024 YU4
2180      31       2    3   4.0  23.392400   2024 YU4
2181      31       2    4  21.0  23.504091   2024 YU4
2182      97       2    2   7.0  23.091375   2024 YU4
2183      97       2    3   3.0  23.205250   2024 YU4

In [87]:
observ2.to_csv("./data/known_binary_asteroids_TESSobserv.txt")

In [59]:
partial_table.iloc[-1]

sector        92.000
camera         1.000
ccd            1.000
dur           25.000
vmag          22.418
target    119067.000
Name: 1453, dtype: float64

In [88]:
with pd.option_context('display.max_rows', None):
    display(observ2.query("vmag > 17"))

      sector  camera  ccd   dur       vmag      target
87        72       3    3  24.0  17.093800         809
101       72       4    3   5.0  17.723833        1169
102       92       2    2  25.0  17.423615        1169
104       45       4    3  20.0  17.319571        1313
105       46       3    3  10.0  17.233909        1313
106       46       4    2  14.0  17.129533        1313
112       72       3    4  16.0  17.056706        1338
116       43       4    4  18.0  17.412000        1344
130       46       4    2  13.0  18.309429        1526
131       46       4    3  11.0  18.232583        1526
145       72       3    4   9.0  17.114300        1770
152       92       3    3  25.0  17.462654        1798
164       71       4    4   4.0  18.947600        1862
165       72       2    2  24.0  18.720960        1862
166     1751       1    1   6.0  19.096286        1862
175       91       4    2  26.0  17.216519        1879
179       50       2    3   7.0  17.379000        1934
185       71       4    2  24.0  17.119880        2019
190       72       4    4  16.0  18.702706        2037
191       92       3    2  11.0  17.545000        2037
192       92       3    3  12.0  17.313615        2037
196     1751       4    3   6.0  17.118857        2070
197       71       4    4  19.0  17.233250        2080
202       45       4    2   7.0  17.699750        2121
203       45       4    3  15.0  17.590375        2121
204       46       3    3  12.0  17.418538        2121
214       43       3    3  24.0  17.160360        2171
221       71       4    3  17.0  17.519667        2280
226       91       4    3  20.0  17.341905        2337
228       72       4    2  16.0  18.759000        2343
229       72       4    3   6.0  18.684000        2343
230       91       3    4  15.0  17.511875        2343
231       42       4    3   2.0  17.550667        2449
232       87       2    3  18.0  17.322053        2449
233       87       2    4   4.0  17.304600        2449
234       92       4    1  23.0  17.092458        2478
243       72       3    4   1.0  17.954000        2516
244       72       4    1  22.0  17.852609        2516
245       92       1    2  25.0  17.912462        2516
252       43       4    2  24.0  17.637760        2602
253       44       2    1  23.0  17.159125        2602
256       43       4    4   9.0  17.499000        2623
257       44       3    4  23.0  17.168833        2623
261       45       4    2  15.0  17.481750        2635
262       45       4    3   7.0  17.344500        2635
263       46       3    3  25.0  17.081269        2635
264       44       4    4  23.0  18.447125        2680
265       45       3    1  24.0  18.207040        2680
266       46       2    3  26.0  17.808926        2680
268       72       3    4  24.0  18.007480        2691
269       92       3    3   9.0  17.896400        2691
270       92       4    2  15.0  17.777250        2691
271       71       3    4   2.0  17.286000        2754
272       71       4    1  21.0  17.091955        2754
274       91       1    1  26.0  17.609222        2754
275       72       3    4  12.0  17.787692        2815
276       72       4    1  11.0  17.665667        2815
280       72       4    1   7.0  18.152625        2825
281       72       4    4  16.0  18.089176        2825
282       92       2    4  23.0  17.559208        2825
283       92       1    1   2.0  17.254667        2825
289       64       1    2  26.0  17.121704        2860
291       72       4    4  24.0  18.062840        2871
296       44       4    2  23.0  18.116458        2873
297       45       2    1   2.0  17.916667        2873
298       45       2    2   5.0  17.540333        2873
299       46       1    2  26.0  17.143889        2873
300       92       4    1   6.0  18.510286        2881
301       92       4    4  17.0  18.414500        2881
302       92       4    3  10.0  18.378182        2883
303       43       4    1   9.0  18.500800        2966
304       44       2    2  23.0  18.184958        2966
305       45       1    3  24.0  17.640560        2966
306     1751       3    3   6.0  17.502143        2966
307       45       4    1  24.0  18.193200        3034
308       46       3    1  26.0  17.864815        3034
311       71       4    2  24.0  17.267280        3073
313       91       4    1  26.0  17.873630        3073
315       72       3    3  24.0  18.308160        3076
316       91       4    1  17.0  17.464778        3076
317       91       3    4   7.0  17.092375        3076
318       10       2    3   5.0  17.398500        3122
319       36       1    3  10.0  17.532364        3122
320       36       1    4  12.0  17.551692        3122
331       72       4    3   2.0  18.357000        3187
332       92       3    3  23.0  17.983500        3187
333       92       4    2   2.0  17.812333        3187
339       11       1    2  27.0  18.553464        3255
341       45       4    4   2.0  18.397000        3255
342       46       4    2  23.0  18.414375        3255
343       46       4    3   1.0  18.355500        3255
344       66       1    1   3.0  18.446750        3255
346       44       3    3  17.0  18.770333        3336
347       44       4    2   5.0  18.612000        3336
348       45       2    4  24.0  18.416500        3336
349       45       2    1   4.0  18.271600        3336
350       46       1    4  26.0  17.790741        3336
353       44       4    1  23.0  18.024500        3378
354       45       2    2   9.0  17.769700        3378
355       45       3    1  13.0  17.538929        3378
356       46       1    2  26.0  17.079556        3378
359       71       4    1  24.0  17.934200        3390
360       72       1    2  24.0  17.382640        3390
366       72       4    1  24.0  17.609280        3433
367       91       4    2  26.0  17.567889        3433
368       92       1    4   2.0  17.233000        3433
373       72       3    3   2.0  17.382000        3533
374       72       4    2  21.0  17.269955        3533
375       92       2    3  25.0  17.211808        3533
377       42       4    4  16.0  17.216000        3548
381       72       3    1  24.0  17.296800        3548
384       91       3    1  26.0  17.069333        3643
386       44       4    3  23.0  17.796208        3657
387       45       3    2  24.0  17.504320        3657
388       46       2    4  26.0  17.048593        3657
389       43       4    1  24.0  17.359440        3658
397       31       1    3  23.0  19.065375        3671
398       44       4    1  23.0  22.525792        3671
399       45       2    2  24.0  22.193960        3671
400       46       1    3  26.0  21.722704        3671
401       47       1    3  27.0  21.432000        3671
405        6       1    3  22.0  17.805522        3703
406       42       3    3  25.0  17.584192        3703
407       43       2    4   9.0  17.153500        3703
410       98       1    3  20.0  17.690286        3703
411     1751       4    1   6.0  18.279714        3703
413       43       4    4   2.0  17.931000        3749
414       44       3    4  13.0  17.507500        3749
415       44       4    1   9.0  17.296300        3749
421       44       4    3  23.0  17.957792        3782
422       45       3    2  20.0  17.655190        3782
423       45       3    3   1.0  17.429500        3782
424       46       2    4  26.0  17.112889        3782
426       43       4    4  24.0  17.251280        3841
430       45       3    3   3.0  18.031250        3865
431       45       4    2  20.0  17.891524        3865
432       46       3    2  26.0  17.522481        3865
441       10       1    4   2.0  17.016333        3905
445       92       4    2  15.0  18.296563        3905
446       92       4    3   8.0  18.142333        3905
451       42       4    4   8.0  18.631444        3927
452       43       3    4  24.0  18.114720        3927
453       44       2    3   7.0  17.767750        3927
454       44       1    2  15.0  17.495250        3927
455     1751       1    3   6.0  17.687143        3927
456       45       4    2  10.0  17.692545        3951
457       45       4    3  12.0  17.621231        3951
458       46       3    3  26.0  17.437370        3951
459       92       3    4  25.0  18.590615        3959
460       42       4    2  25.0  17.662154        3969
461       43       2    1  24.0  17.022000        3969
465       72       3    2  24.0  18.038200        3982
469       46       4    2   5.0  17.864167        4029
470       46       4    3  19.0  17.742150        4029
474       44       3    4  23.0  18.297292        4030
475       45       2    3  24.0  17.874320        4030
476       46       1    3  20.0  17.378524        4030
477       47       1    3  18.0  17.000526        4030
480       44       4    3  23.0  18.608417        4092
481       45       3    2  24.0  18.399080        4092
482       46       2    4  26.0  18.042111        4092
483     1751       3    1   6.0  17.004429        4092
486       72       3    3  24.0  17.781880        4272
492       70       4    1  14.0  18.138467        4337
493       70       3    4  10.0  17.937636        4337
494       71       1    2  24.0  17.562800        4337
495        2       1    4  17.0  17.036167        4350
502       72       3    1  24.0  17.391880        4362
503       92       3    2   2.0  17.638667        4362
504       92       3    3  21.0  17.480136        4362
508     1751       1    3   6.0  17.927429        4370
509       92       3    1   3.0  18.077750        4373
510       92       3    4  20.0  17.847857        4373
515       44       4    4   9.0  18.163200        4411
516       45       3    4  15.0  17.835687        4411
517       46       2    2  26.0  17.401778        4411
518       11       2    3  25.0  17.965577        4435
519       27       1    3   8.0  17.257333        4435
520       45       4    1   0.0  17.281000        4435
521       45       4    4  22.0  17.267522        4435
522       46       3    4   8.0  17.219556        4435
523       46       4    1   2.0  17.189000        4435
524       46       4    2  11.0  17.120083        4435
525       66       1    2  26.0  18.148593        4435
529       12       1    4  22.0  17.850478        4492
530       44       4    1  23.0  17.992333        4492
531       45       2    2  18.0  17.726368        4492
532       45       3    1   4.0  17.530200        4492
533       46       1    2  26.0  17.230519        4492
535       44       4    1   8.0  18.076778        4494
536       45       2    2   8.0  17.667333        4494
537       45       3    2   3.0  17.272500        4494
539       31       1    4  27.0  17.873607        4514
540       45       4    1  24.0  18.606440        4514
541       46       3    1  10.0  18.339273        4514
542       46       3    4  15.0  18.100875        4514
545       69       1    4  24.0  17.636400        4514
548       45       4    2  24.0  17.110640        4528
552       43       4    4   1.0  18.032500        4541
553       44       3    4  23.0  17.574708        4541
554       45       2    3  24.0  17.097320        4541
556       45       3    3   2.0  18.395667        4605
557       45       4    2  21.0  18.296773        4605
558       46       3    2  26.0  18.001222        4605
559       42       4    4  12.0  17.821462        4607
560       43       3    4  24.0  17.233640        4607
563       34       2    3  25.0  17.365731        4666
565       71       3    3   7.0  18.125250        4666
575     1751       4    3   6.0  17.044000        4765
576        4       1    4   4.0  17.233000        4786
577       72       4    1  21.0  18.234182        4786
578       72       4    4   1.0  18.057000        4786
579       92       4    3  19.0  18.442100        4786
580       97       1    4   0.0  17.014000        4786
581       45       4    3  17.0  18.976889        4788
582       46       3    3   2.0  18.889000        4788
583       46       4    2  23.0  18.778667        4788
584       36       1    4  23.0  17.100333        4868
585       98       2    3  29.0  18.060167        4868
586       35       1    3   0.0  17.185000        4901
588       72       3    2  24.0  18.494320        4901
590       71       4    3   2.0  17.533667        4951
591       72       3    1  24.0  17.044160        4951
592       91       4    4  26.0  18.100074        4951
593       92       1    3  25.0  17.528308        4951
594       92       4    1  25.0  18.230385        5037
595       72       3    4   6.0  18.430143        5112
596       72       4    1  17.0  18.314889        5112
597       92       2    4  25.0  17.822885        5112
601       44       4    1  23.0  18.568542        5135
602       45       2    2  12.0  18.283462        5135
603       45       3    1  11.0  18.053083        5135
604       46       1    2  26.0  17.595148        5135
605       43       4    1   0.0  17.117000        5143
606        5       1    3  20.0  17.087952        5232
607        5       1    4   1.0  17.123000        5232
608       82       2    1   2.0  17.282667        5261
609       82       3    2  20.0  17.229095        5261
610       83       3    1  10.0  17.210727        5261
611       34       1    3   6.0  17.018000        5319
613       71       4    2  24.0  18.398920        5319
614       72       1    1  24.0  17.910480        5319
620        5       1    4  24.0  17.477280        5407
621       44       4    3  23.0  18.623917        5407
622       45       3    2   8.0  18.300778        5407
623       45       3    3  14.0  18.000400        5407
624       46       2    1  10.0  17.622636        5407
625       46       2    2  11.0  17.121750        5407
628       92       4    2   1.0  18.232500        5407
629       92       4    3  22.0  18.230739        5407
632       71       4    1  24.0  17.434880        5425
635       91       1    1  10.0  17.211182        5425
639       42       4    1  24.0  17.724480        5474
640       43       2    2  24.0  17.150280        5474
648       42       4    3   7.0  17.864000        5477
649       43       3    3  24.0  17.202120        5477
654       44       4    1  11.0  18.292250        5481
655       44       4    4  10.0  18.134455        5481
656       45       3    1  24.0  17.824920        5481
657       46       2    3  26.0  17.250963        5481
659       72       4    1  17.0  18.280667        5500
660       72       4    4   5.0  18.167500        5500
661       92       2    2  10.0  18.328455        5500
667       22       1    3   6.0  19.662857        5646
668     1751       1    1   6.0  19.300857        5646
669       71       4    4   3.0  18.437250        5674
670       72       2    2   0.0  18.198000        5674
671       72       3    1  23.0  18.023458        5674
673       59       1    3   3.0  17.042750        5772
674       72       4    2  24.0  18.541040        5772
681       37       1    2  11.0  17.641333        5817
682       71       3    4   5.0  17.245000        5872
685       91       2    4  26.0  17.073370        5872
686       77       1    4   1.0  17.403500        5899
687       78       1    3  10.0  17.411455        5899
692        5       1    1   7.0  17.045375        6009
696       46       4    2  16.0  19.258353        6016
697       46       4    3   8.0  19.150000        6016
698       72       4    4  24.0  17.929200        6084
702       43       4    1  24.0  17.598880        6098
703       44       2    2  23.0  17.159917        6098
705       70       4    4  24.0  17.085400        6100
707       91       1    4  26.0  17.551704        6100
708       45       3    4   2.0  18.122667        6177
709       45       4    1  21.0  17.985045        6177
710       46       3    1  21.0  17.663545        6177
711       46       3    4   3.0  17.415000        6177
712       11       1    4  27.0  18.048286        6181
713       45       4    2  24.0  18.586200        6181
714       46       3    2  26.0  18.354148        6181
715       65       1    3  15.0  17.953063        6181
716       65       1    4   9.0  17.918800        6181
719       92       3    3   5.0  18.093667        6244
720       92       4    2  19.0  17.918200        6244
721       92       4    4   0.0  17.759000        6245
722       45       3    4   2.0  18.906333        6265
723       45       4    1  21.0  18.791318        6265
724       46       3    1  26.0  18.459000        6265
725       48       1    4  14.0  17.110400        6265
729       46       4    3   5.0  18.233833        6326
732     1751       3    3   6.0  17.496714        6369
735       49       2    1   0.0  17.011000        6384
737       92       2    3  25.0  18.308231        6611
738       42       3    3  25.0  18.917615        6615
739       43       2    4  24.0  18.326160        6615
740     1751       1    3   6.0  17.404714        6615
741       72       3    4  24.0  18.662680        6690
742       92       3    2  25.0  17.177308        6690
744       22       1    3  27.0  17.237321        6708
745       72       4    4  24.0  18.861960        6708
746       92       3    3  17.0  17.347833        6708
747       92       4    2   8.0  17.186667        6708
753       72       3    4  16.0  18.286059        6764
754       72       4    1   7.0  18.109750        6764
755       92       4    2  21.0  17.732364        6764
756       92       4    3   3.0  17.632750        6764
757       70       3    1   7.0  17.317250        6809
758       70       2    2  16.0  17.010353        6809
760       72       3    2   7.0  17.218250        6974
761       72       3    3   3.0  17.046500        6974
762       72       4    2  24.0  20.709200        7002
763       91       3    4  26.0  18.165111        7002
764       23       1    2   3.0  17.614750        7088
765        4       1    4  11.0  17.334083        7089
767       97       1    3   0.0  17.754000        7089
768       42       2    3  25.0  17.596231        7132
769       59       1    4  23.0  17.253792        7132
770       45       4    3  21.0  18.432455        7187
771       46       3    3   4.0  18.321200        7187
772       46       4    2  21.0  18.190364        7187
775       42       4    1  25.0  17.307462        7225
778       82       1    4   2.0  17.087000        7225
779       82       1    3  19.0  17.016700        7225
788       46       4    1   1.0  18.846500        7355
789       46       4    4  23.0  18.761750        7355
795       62       2    3   7.0  17.558000        7369
802     1751       1    4   6.0  17.318571        7393
805       44       4    1   6.0  18.686857        7500
806       44       4    4  15.0  18.565875        7500
807       45       3    1  24.0  18.285000        7500
808       46       2    3  26.0  17.800296        7500
809       92       3    3  25.0  18.762692        7563
810       95       1    3  24.0  17.679520        7563
811       72       3    1  12.0  19.261692        7615
812       72       3    4  10.0  19.107182        7615
813       91       2    2  26.0  17.535815        7615
814       71       3    4  16.0  17.560235        7792
815       71       4    1   7.0  17.293500        7792
819       40       1    3   5.0  19.799833        7888
820       54       1    1   9.0  21.114200        7888
823       51       4    4   7.0  17.054500        7889
824       51       4    1  13.0  17.128786        7889
825       43       4    1  24.0  18.245160        7930
826       44       2    2  23.0  17.836167        7930
827       45       1    3  18.0  17.385842        7930
828       63       1    4  20.0  18.693381        7930
830     1751       1    3   6.0  18.990714        7930
831        7       2    3  12.0  17.117077        7958
832       46       4    2   3.0  18.948250        7958
833       46       4    3  21.0  18.847136        7958
835       87       2    3   2.0  17.348333        8026
836       87       2    4  20.0  17.389095        8026