In [3]:
from glob import glob
import pandas as pd
import numpy as np

In [7]:
df = pd.DataFrame(index=np.arange(1,27), columns=[f"{C}-{c}" for C in range(1,5) for c in range(1,5)])
df

,1-1,1-2,1-3,1-4,2-1,2-2,2-3,2-4,3-1,3-2,3-3,3-4,4-1,4-2,4-3,4-4
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
for sec in df.index.values:
    for cam in range(1,5):
        for ccd in range(1,5):
            fnames = sorted(glob(f"/Users/jimartin/Work/TESS/tess-asteroid-ml/data/pred_asteroid_tracks/candidate_files/track_candidate_TESS_{sec}_{cam}_{ccd}_*.csv"))
            df.loc[sec, f"{cam}-{ccd}"] = len(fnames)

In [11]:
df

   1-1 1-2 1-3 1-4 2-1 2-2 2-3 2-4 3-1 3-2 3-3 3-4 4-1 4-2 4-3 4-4
1    0   0   0   0   2   4   6   9   0   0   0   0   0   0   0   0
2    0   0   0   0   6   5   4  39   6   5   1   0   0   0   0   0
3   55  43  22  46   7   6  14  16   4   5   0   1   0   0   0   0
4    0   0   0   0   5   5   9  10   4   0   1   0   0   0   0   0
5    0   0   0   0   1   7   3   3   0   1   0   0   0   0   0   0
6    0   0   0   0   2   0   1   0   4   0   0   1   0   0   0   0
7    0   0   0   0   1   1   1   0   0   0   1   0   0   0   0   0
8    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
9    0   0   0   0   3   3   5   8   1   0   0   0   0   0   0   0
10   0   0   0   0   2   3   4  15   0   1   1   0   0   1   0   0
11   0   0   0   0   2   0   0  10   1   1   0   0   1   1   0   0
12   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
13   0   0   0   0   1   1  12  12   1   0   0   2   2   0   0   0
14   0   0   0   0   0   0   0   0   2   0   2   2   0   0   0   3
15   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
16   0   0   0   0   0   0   0   0   1   3   1   0   0   2   0   2
17   0   0   0   0   0   0   0   0   0   0   0   0   0   1   2   0
18   0   0   0   0   1   5   4   1   0   3   0   0   2   1   3   0
19   0   0   0   0   1   6   4  11   0   0   0   0   0   0   3   0
20   0   0   0   0   2   6   2  13   0   0   0   0   0   0   4   0
21   0   0   0   0   2   0   1   0   2   1   0   0   0   0   2   1
22   0   0   0   0   0   0   0   0   0   0   0   0   0   1   1   2
23   0   0   0   0   0   0   0   0   0   0   0   0   0   1   0   1
24   0   0   0   0   1   0   0   0   0   0   0   0   0   0   0   0
25   0   0   0   0   2   0   0   0   1   1   0   0   0   0   0   0
26   0   0   0   0   0   2   0   1   1   1   0   0   0   1   0   0